### ISSUE TITLE
Circuit Breaker TImed out error

### ISSUE THREAD

**Issue by odwrotnie** [lagom/online-auction-scala#33]
When you runAll and go to / you get this:

```
! @73ghf5b2j - Internal server error, for (GET) [/createuser] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[$anon$1: Circuit Breaker Timed out.]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:293)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
Caused by: akka.pattern.CircuitBreaker$$anon$1: Circuit Breaker Timed out.
[error] application - 

```

**Comment by TimMoore** [comment]
@odwrotnie I'm not able to reproduce this... any extra information you can provide that would help us identify the problem would be helpful.

To start, could you provide the full console output? There may be another error hidden in there that is causing this one.

Also, when you say "go to /" do you mean you're loading "http://localhost:9000/" in a browser, or are you trying to hit one of the service ports directly? Does this happen on the very first page? The error mentions "/createuser" which I think would only be triggered by clicking "Create user" from the main page (which also works for me).

**Comment by TimMoore** [comment]
@odwrotnie is this still an issue for you?

**Comment by odwrotnie** [comment]
No, it have been fixed.
